### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by emersion** [rahra/cairo_jpg#2]
The current license ("This code is free software. Do whatever you like to do with it.") is not a well-known license. This causes issue with packaging, for instance Debian requires the license to follow the [DFSG guidelines](https://wiki.debian.org/DFSGLicenses). See https://github.com/emersion/grim/issues/34

**Comment by rahra** [comment]
Well, it's the well-known "beer license" ;-) 🍺
Ok, I'll update that accordingly.

**Comment by rahra** [comment]
Added LGPL, same as Cairographics.

**Comment by emersion** [comment]
Thanks!
