### ISSUE TITLE
possible memory leak?

### ISSUE THREAD

**Issue by xielei296** [rahra/cairo_jpg#3]
hi, rahra, possibly a problem? 
case : if cairo_image_surface_write_to_jpeg_mem return error, memory allocaged to the pointer  "data" may leak

**Comment by rahra** [comment]
Where exactly do you think the memory leak occurs?
The memory is not allocated before line 194 at `jpeg_mem_dest(&cinfo, data, len);` and errors are returned before this.

**Comment by xielei296** [comment]
memory allocated at line 408, 
at line 437 returns error, 
at line 356 --> leak

**Comment by rahra** [comment]
Oh yes, you are right.
I fixed it in 2a0dff5ad313fdb8db3112eaf635bd56516ddf49.
