### ISSUE TITLE
Could not find/open device

### ISSUE THREAD

**Issue by xevilstar** [rahra/cairo_jpg#4]
[30940.091717] usb 1-2.1: new high-speed USB device number 9 using xhci_hcd
[30940.219150] usb 1-2.1: New USB device found, idVendor=09cb, idProduct=1996, bcdDevice= 1.08
[30940.219155] usb 1-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[30940.219156] usb 1-2.1: Product: FLIR ONE Camera
[30940.219157] usb 1-2.1: Manufacturer: FLIR Systems
[30940.219158] usb 1-2.1: SerialNumber: T05L4T000EB
[30943.171647] usb 1-2.1: USB disconnect, device number 9

root@ghost:/usr/src/flir-gtk# make
gcc -g -O2 -Wall -D_REENTRANT `pkg-config --cflags gtk+-3.0 libusb-1.0 libjpeg libcjson`   -c -o flirgtk.o flirgtk.c
gcc -g -O2 -Wall -D_REENTRANT `pkg-config --cflags gtk+-3.0 libusb-1.0 libjpeg libcjson`   -c -o cam-thread.o cam-thread.c
gcc -g -O2 -Wall -D_REENTRANT `pkg-config --cflags gtk+-3.0 libusb-1.0 libjpeg libcjson`   -c -o cairo_jpg/src/cairo_jpg.o cairo_jpg/src/cairo_jpg.c
gcc flirgtk.o cam-thread.o cairo_jpg/src/cairo_jpg.o -o flirgtk `pkg-config --libs gtk+-3.0 libusb-1.0 libjpeg libcjson` -lm
root@ghost:/usr/src/flir-gtk# make install
install -D flirgtk /usr/local/bin/flirgtk
install -D flirgtk.desktop /usr/local/share/applications/flirgtk.desktop
install -D flirgtk.png /usr/local/share/icons/hicolor/256x256/apps/flirgtk.png
install -D 77-flirone-lusb.rules /lib/udev/rules.d/77-flirone-lusb.rules
root@ghost:/usr/src/flir-gtk# cp -rp /usr/local/share/applications/flirgtk.desktop /usr/share/applications/
Display all 697 possibilities? (y or n)
root@ghost:/usr/src/flir-gtk# cp -rp /usr/local/share/applications/flirgtk.desktop /usr/share/applications/
root@ghost:/usr/src/flir-gtk# cp -rp /usr/local/share/icons/hicolor/256x256/apps/flirgtk.png /usr/share/icons/hicolor/256x256/apps/flirgtk.png
root@ghost:/usr/src/flir-gtk# udevadm control --reload-rules
root@ghost:/usr/src/flir-gtk# flir
flir-GetThermal  flirgtk          
root@ghost:/usr/src/flir-gtk# flir
flir-GetThermal  flirgtk          
root@ghost:/usr/src/flir-gtk# flirgtk 
Could not find/open device
Could not find/open device

**Comment by psychon** [comment]
Sorry, but what is your problem with cairo_jpg? I do not know what you are showing in your post, but cairo_jpg does not even have a Makefile. :confused:

**Comment by rahra** [comment]
I think that has nothing to do with cairo_jpg.
